language: python
os:
  - linux
  - osx
osx_image: xcode9.2
python:
  - "2.7"
install:
  - export NUGITHUB=https://github.com/eliteraspberries/nu/releases/download
  - curl -L -o libnu.so $NUGITHUB/v0.1/libnu-0.1-$(uname -s)-$(uname -m).so
  - pip install -r requirements.txt
script:
  - py.test
