language: python
os:
  - linux
  - osx
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
matrix:
  allow_failures:
  - os: osx
  - python: "3.7"
  - python: "pypy"
install:
  - export NUGITHUB=https://github.com/eliteraspberries/nu/releases/download
  - curl -L -o libnu.so $NUGITHUB/v0.3/libnu-0.3-$(uname -s)-$(uname -m).so
  - pip install -r requirements.txt
script:
  - py.test
